stages:
  - build
  - test

# variables:
#     CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

# cache:
#   key:
#     files:
#       - pnpm-lock.yaml
#   paths:
#     - .pnpm-store
#     - .cache/*
#     - cache/Cypress
#     - node_modules
#     - dist


default:
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1

.standard-before_script:
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store


## Install npm dependencies and Cypress
install:
  stage: build
  extends:
    - .standard-before_script
  script:
    - pnpm install
    - pnpm run build
  artifacts:
    paths:
      - "dist/"

ui-chrome-tests:
  stage: test
  # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
  # in GitLab repo → Settings → CI/CD → Variables
  variables:
    CYPRESS_RECORD_KEY: $CYPRESS_RECORD_KEY
  parallel: 2 # Uses 2 parallel instances
  extends:
    - .standard-before_script
  script:
    - pnpm install
    - pnpm run test:e2e:record
