stages:
  - test

ui-chrome-tests:
  # Uses official Cypress docker image for dependencies
  # https://docs.cypress.io/guides/continuous-integration/introduction#Official-Cypress-Docker-Images
  image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
  stage: test
  # For recording and parallelization to work you must set your CYPRESS_RECORD_KEY
  # in GitLab repo → Settings → CI/CD → Variables
  variables:
    CYPRESS_RECORD_KEY: $CYPRESS_RECORD_KEY
    CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'
  parallel: 2 # Uses 2 parallel instances
  before_script:
    - corepack enable
    - corepack prepare pnpm@latest-8 --activate
    - pnpm config set store-dir .pnpm-store
  script:
    - pnpm install
    - pnpm run build
    - pnpm run test:e2e:record
  # cache:
  #   key:
  #     files:
  #       - pnpm-lock.yaml
  #   paths:
  #     - .pnpm-store
  #     - cache/Cypress
  #     - .cache/*
  #     - node_modules